version: 2

before:
  hooks:
    - go mod tidy

builds:
  - id: mayla-linux
    main: ./cmd/mayla
    binary: mayla
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w
      - -X github.com/alucardeht/may-la-mcp/pkg/version.Version={{ .Version }}
      - -X github.com/alucardeht/may-la-mcp/pkg/version.Commit={{ .Commit }}
      - -X github.com/alucardeht/may-la-mcp/pkg/version.BuildDate={{ .Date }}

  - id: mayla-daemon-linux
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w
      - -X github.com/alucardeht/may-la-mcp/pkg/version.Version={{ .Version }}
      - -X github.com/alucardeht/may-la-mcp/pkg/version.Commit={{ .Commit }}
      - -X github.com/alucardeht/may-la-mcp/pkg/version.BuildDate={{ .Date }}

archives:
  - id: linux
    builds:
      - mayla-linux
      - mayla-daemon-linux
    format: binary
    name_template: "{{ .Binary }}-{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: 'checksums_linux.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

release:
  mode: append
