version: 2

before:
  hooks:
    - go mod tidy

env:
  - CGO_ENABLED=1

builds:
  # mayla CLI
  - id: mayla-linux-amd64
    main: ./cmd/mayla
    binary: mayla
    goos: [linux]
    goarch: [amd64]
    env:
      - CC=zig cc -target x86_64-linux
      - CXX=zig c++ -target x86_64-linux
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-linux-arm64
    main: ./cmd/mayla
    binary: mayla
    goos: [linux]
    goarch: [arm64]
    env:
      - CC=zig cc -target aarch64-linux
      - CXX=zig c++ -target aarch64-linux
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-darwin-amd64
    main: ./cmd/mayla
    binary: mayla
    goos: [darwin]
    goarch: [amd64]
    env:
      - CC=zig cc -target x86_64-macos
      - CXX=zig c++ -target x86_64-macos
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-darwin-arm64
    main: ./cmd/mayla
    binary: mayla
    goos: [darwin]
    goarch: [arm64]
    env:
      - CC=zig cc -target aarch64-macos
      - CXX=zig c++ -target aarch64-macos
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-windows-amd64
    main: ./cmd/mayla
    binary: mayla
    goos: [windows]
    goarch: [amd64]
    env:
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-windows-arm64
    main: ./cmd/mayla
    binary: mayla
    goos: [windows]
    goarch: [arm64]
    env:
      - CC=zig cc -target aarch64-windows-gnu
      - CXX=zig c++ -target aarch64-windows-gnu
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  # mayla-daemon
  - id: mayla-daemon-linux-amd64
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos: [linux]
    goarch: [amd64]
    env:
      - CC=zig cc -target x86_64-linux
      - CXX=zig c++ -target x86_64-linux
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-daemon-linux-arm64
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos: [linux]
    goarch: [arm64]
    env:
      - CC=zig cc -target aarch64-linux
      - CXX=zig c++ -target aarch64-linux
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-daemon-darwin-amd64
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos: [darwin]
    goarch: [amd64]
    env:
      - CC=zig cc -target x86_64-macos
      - CXX=zig c++ -target x86_64-macos
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-daemon-darwin-arm64
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos: [darwin]
    goarch: [arm64]
    env:
      - CC=zig cc -target aarch64-macos
      - CXX=zig c++ -target aarch64-macos
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-daemon-windows-amd64
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos: [windows]
    goarch: [amd64]
    env:
      - CC=zig cc -target x86_64-windows-gnu
      - CXX=zig c++ -target x86_64-windows-gnu
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

  - id: mayla-daemon-windows-arm64
    main: ./cmd/mayla-daemon
    binary: mayla-daemon
    goos: [windows]
    goarch: [arm64]
    env:
      - CC=zig cc -target aarch64-windows-gnu
      - CXX=zig c++ -target aarch64-windows-gnu
    flags:
      - -tags=sqlite_fts5
    ldflags:
      - -s -w

archives:
  - format: binary
    name_template: "{{ .Binary }}-{{ .Os }}-{{ .Arch }}"

changelog:
  disable: true

release:
  draft: false
  prerelease: false
